- id: '123456789'
  alias: some_automation_name_1
  description: ''
  trigger:
  - type: plugged_in
    platform: device
    device_id: 1234567890
    entity_id: binary_sensor.some_binary_sensor_1
    domain: binary_sensor
  condition:
  - condition: time
    after: '01:00:00'
    before: 02:00:00
  action:
  - scene: scene.some_scene_name_1
  mode: single
- id: '987654321'
  alias: some_automation_name_2
  description: ''
  trigger:
  - type: plugged_in
    platform: device
    device_id: 0987654321
    entity_id: binary_sensor.some_binary_sensor_2
    domain: binary_sensor
  condition:
  - condition: time
    after: '02:00:00'
    before: 03:00:00
  action:
  - scene: scene.some_scene_name_2
  mode: single
- id: 'some_automation_name_3'
  alias: some_automation_name_3
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.some_input_number_3
    from: '42'
    to: '43'
  condition:
  - condition: time
    after: '02:00:00'
    before: 03:00:00
  action:
  - scene: scene.some_scene_name_2
  mode: single